apiVersion: v1
kind: Secret
metadata:
    name: weave-gitops-secret
    namespace: flux-system
type: Opaque
stringData:
    adminPassword: ENC[AES256_GCM,data:UGSk6cMoMnr5GYjq575VxNnJcyhvMoDKAwH8Lq3P459H5/dnQQYUqsbCPuAsuydArofotq3eGy62RmWQ,iv:prjW8TdumHJH4Uyv3iJiIQKZ+Q1Y6aWda8SXrZe270M=,tag:tJWFBrAXLOGJJvrfoP03RA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age13ln6jzm5f6auwyc2sc3kn2d2uh09vgvk69gl565g7fy4rfxh2slqc59s75
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXVWZCRmNZMWRxQ3YvWm5R
            aXBaS1VNZklXVk1CaTU5OUtLSGlqS2VxUUhVCjJJUS9WK21uMVl6NHUvaXo0Vmhp
            V3U2TURSMk5MSHJKdmRqeFp0ZnpUY0EKLS0tIFhhTDlhWFl5QUpsQlFiY3FSMjY1
            SHR5aUpHNGdHRzdGaXRqTkZNTExXTkEKCzQuIYF3uykYRDbsYALhSGgSVHsHYy5a
            C4OdsSemEq+TUmRt3AXkKPRyvslifcgRXfADc/JJmU2lqdF5YkgiVg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-02-25T05:12:06Z"
    mac: ENC[AES256_GCM,data:A6BJERyKZfAsBP1FyiE18977G1Enu55KT0KZzcrJB1f4ikSS02KcqGYmzfDs6o6jgqy1J+Cp8f0rp4ZRvBXpckF3eM+kUgl5xwrkmpO9PhJNPTS0PvrwQvWWT+ww1q1F3sJsh6pDi8v/b8k2pqqykIghElqQTDtdyIlnrBlfQL8=,iv:QknHYk0La6veqbWXS/yjNDLtmqZN5OW1DmlcghWt2b8=,tag:7ul4Jx1DR8wIZI1gBpPJQw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
