---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/Chicago"
  KUBE_VIP_ADDR: "192.168.78.71"
  METALLB_LB_RANGE: "192.168.78.60-192.168.78.70"
  METALLB_K8S_GATEWAY_ADDR: "192.168.78.60"
  METALLB_INGRESS_ADDR: "192.168.78.61"
